libs =
import libs += roguey-deps%liba{roguey-deps}

exe{roguey}: {hxx ixx txx cxx mxx}{**} file{scripts/**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base/include"

if($cxx.target.system != 'win32-msvc')
{
    cxx.libs += -lpthread -lncurses -lm
}

file{scripts/**} :
{
    install = bin/scripts/
    install.subdirs = true
}
